### ISSUE TITLE
Decompressor error in hadoop: incorrect header check

### ISSUE THREAD

**Issue by Yikun** [kunpengcompute/KAEzip#12]
![1](https://user-images.githubusercontent.com/1736354/93187726-b5ffe400-f772-11ea-8ff2-c03dfeaec271.png)

The hadoop decompressor calls inflate reset and inflate interface, but looks like the kaezip doesn't rewrite the inflate reset, then the kae context doesn't reset successfully.

![2](https://user-images.githubusercontent.com/1736354/93187755-bac49800-f772-11ea-93fe-a7856a053f21.png)

the above pic shows the zlib and kae data diff.

**Comment by Yikun** [comment]
the potential solution is that we should rewrite the zlib inflate reset method with kae init in KAEzip, see more in https://github.com/Yikun/KAEzip/commit/dec59176df5b103ff1f1bb9d6dfe3b4e8f4e45c9

**Comment by yuhongxiao123456** [comment]
this issue has been fixed in v1.3.9
