### ISSUE TITLE
Autodetect (windowsBits 47) cannot be identified

### ISSUE THREAD

**Issue by Yikun** [kunpengcompute/KAEzip#13]
The Gzip/Zlib compress data use compression header.windowsBits=47 to represents the "Autodetect gzip/zlib headers/trailers."

But the KAEZip doen't support it. [1] 

[1] https://github.com/kunpengcompute/KAEzip/blob/ab25510ffa5beb228d6fb2fd38599d7eefc12b34/src/kaezip_common.c#L103

**Comment by yuhongxiao123456** [comment]
v1.3.9 fix this issue.
